<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <PackageReference Include="Telegram.Bot" Version="22.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientLibrary\ClientLibrary.csproj" />
  </ItemGroup>

</Project>
